<?php


$labels['rawsievetitle'] = 'Raw filters';
$labels['filtersets'] = 'Filters list';
$labels['add_filter'] = 'Add new filter';
$labels['delete_filter'] = 'Delete selected filter';
$labels['activate'] = 'Activate';
$labels['deactivate'] = 'Deactivate';
$labels['save'] = 'Save script';
$labels['insert_raw_code'] = 'Insert raw script code';
$labels['deletemessage'] = 'Do you really want to delete the script ? This action can\'t be undone.';
$labels['noscritpselected'] = 'You have to select at least one filter';



?>